/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.kudagonewsapp

import com.example.kudagonewsapp.getMostRatedNewsUsingLoops
import com.example.kudagonewsapp.getMostRatedNewsUsingSequences
import com.example.kudagonewsapp.getNews
import kotlinx.coroutines.runBlocking
import kotlinx.datetime.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() = runBlocking {
    val newsList = getNews(200)
    println("---------------------------------")
    println(newsList.size)
    newsList.forEach { println(it) }
    println("---------------------------------")

    // период для  новостей
    val today = Clock.System.now().toLocalDateTime(timeZone = kotlinx.datetime.TimeZone.UTC).date
    val period = today.minus(30, DateTimeUnit.DAY)..today

    // наиболее рейтинговые циклами
    val mostRatedNewsUsingLoops = newsList.getMostRatedNewsUsingLoops(5, period)
    println("Most Rated News (Using Loops):")
    mostRatedNewsUsingLoops.forEach { println(it) }

    println("---------------------------------")

    // наиболее рейтинговые новости  последовательносями
    val mostRatedNewsUsingSequences = newsList.getMostRatedNewsUsingSequences(5, period)
    println("Most Rated News (Using Sequences):")
    mostRatedNewsUsingSequences.forEach { println(it) }


    println("---------------------------------")
    // Фильтруем новости у которых place не null
    val newsWithPlace = newsList.filter { it.place != null }
    println("News with non-null place:")
    newsWithPlace.forEach { println(it) }

}
